/*
 * refactoring-together
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"refactoring-together/src/infrastructure/server/router"
)

func main() {
	log.Printf("Server started")

	router := router.NewRouter()

	log.Fatal(router.Run(":8080"))
}
