/*
 * refactoring-together
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package router

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetRoomQuestions - Get User Info by User ID
func GetRoomQuestions(c *gin.Context) {
	c.JSON(http.StatusCreated, c.Param("roomId"))
}
