/*
 * refactoring-together
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package router 

// Question - 
type Question struct {

	// Unique identifier for the given user.
	Id *interface{} `json:"id"`

	// Unique identifier for the given user.
	UserId *interface{} `json:"userId"`

	// Unique identifier for the given user.
	RoomId *interface{} `json:"roomId"`

	Text *interface{} `json:"text"`

	Code *interface{} `json:"code"`

	// The date that the user was created.
	CreateDate *interface{} `json:"createDate,omitempty"`

	// The date that the user was created.
	UpdateDate *interface{} `json:"updateDate,omitempty"`
}
