name: backend test
run-name: backend test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: scripts
    steps:
      - run: pwd
      - run: ls
      - run: docker-compose up
      - run: go test ./...
